[run]
init_cmds = [
	["go", "install"],
	["go", "build","-ldflags","-s"],
	["./hemacms"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = [
	"$WORKDIR",
	"$WORKDIR/ctrl/admin",
	# "$WORKDIR/ini",
	"$WORKDIR/common",
	"$WORKDIR/middle"
]						# Directories to watch
watch_exts = [".go"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
graceful_kill = false				# Wait for exit and before directly kill
cmds = [
	["go", "install"],
	["go", "build","-ldflags","-s"],
	["./hemacms"]
]									# Commands to run

[sync]
listen_addr = ":6060"
remote_addr = ":6060"
